# Generated by Django 2.2.1 on 2019-05-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_admin', '0001_initial'),
        ('os_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='property/')),
                ('size', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('facing', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('add_date', models.DateField(auto_now=True)),
                ('sold_date', models.DateField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_admin.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sold', models.DateField()),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
        migrations.CreateModel(
            name='BlockProperty',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('block_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
    ]
