# Generated by Django 2.2.1 on 2019-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_agent', '0003_auto_20190531_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockproperty',
            name='amount',
        ),
        migrations.AlterField(
            model_name='blockproperty',
            name='block_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
