# Generated by Django 2.2.1 on 2019-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_agent', '0004_auto_20190604_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproperty',
            name='date_of_sold',
            field=models.DateField(auto_now_add=True),
        ),
    ]
