# Generated by Django 2.2.1 on 2019-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('contactno', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='agent/')),
                ('address', models.TextField()),
                ('contactno', models.IntegerField()),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
